### ISSUE TITLE
CSimpleSocket::Shutdown ignores CShutdownMode-Parameter

### ISSUE THREAD

**Issue by juliusbaechle** [DFHack/clsocket#24] opened 2021-11-15 15:58 UTC
SimpleSocket.cpp, 502 is nRetVal = (CSocketError)shutdown(m_socket, **CSimpleSocket::Sends**);
but must be nRetVal = (CSocketError)shutdown(m_socket, **nShutdown**);

**Comment by lethosor** [comment] 2022-04-07 18:23
Duplicate of #6

**Closed by lethosor** 2022-04-07 18:23 UTC
